name: Deploy to DigitalOcean

on:
    push:
        branches:
            - production

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - name: Copy file via scp
              uses: appleboy/scp-action@master
              env:
                  HOST: ${{ secrets.HOST }}
                  USERNAME: ${{ secrets.USERNAME }}
                  PORT: ${{ secrets.PORT }}
                  KEY: ${{ secrets.SSHKEY }}
              with:
                  source: "."
                  target: "/home/ben/broumvirate-com"

            - name: Run startup script
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  USERNAME: ${{ secrets.USERNAME }}
                  PORT: ${{ secrets.PORT }}
                  KEY: ${{ secrets.SSHKEY }}
                  script: chmod +x /home/ben/broumvirate-com/start.sh; /home/ben/broumvirate-com/start.sh